// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.30.2
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface CreateUserRequestDto {
  email: string;
  password: string;
  firstname?: string | undefined;
  lastname?: string | undefined;
}

export interface SigninDto {
  email: string;
  password: string;
}

export interface CreateUserResponseDto {
  id: string;
  email: string;
  firstname?: string | undefined;
  lastname?: string | undefined;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  create(request: CreateUserRequestDto): Observable<CreateUserResponseDto>;

  signIn(request: SigninDto): Observable<CreateUserResponseDto>;
}

export interface UserServiceController {
  create(
    request: CreateUserRequestDto,
  ): Promise<CreateUserResponseDto> | Observable<CreateUserResponseDto> | CreateUserResponseDto;

  signIn(
    request: SigninDto,
  ): Promise<CreateUserResponseDto> | Observable<CreateUserResponseDto> | CreateUserResponseDto;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create", "signIn"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
