version: '3.9'
services:
  user-db:
    image: postgres:13.18
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - user-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
    driver: 'local'
